### ISSUE TITLE
Cursed Barrel 1.20.1?

### ISSUE THREAD

**Issue by Dumpling00** [quinn-semele/cursed-barrels#1]
Hello! I know this was a joke mod but I actually Really enjoy the idea of having an expanded barrel where half of it could just sit under the floor. It's an amazing solution for optimized storage.

Any chance this could be backported to 1.20.1 Fabric? That would be amazing. I know you said this may find its way to Expanded Storage but I personally would really enjoy the possibility of just having barrels act like vanilla chests, only expandable vertically instead of horizontally, so even as its own little mod I think this is actually genius and incredibly valuable.

Thank you for your time and consideration!

**Comment by quinn-semele** [comment]
Hmmm shouldn't take too long to backport, will see if I have time later today to fix up a few minor issues for 1.20.4 and release it for 1.20.1 as well.
